[package]
name = "mobile"
version = "0.1.0"
authors = ["you"]
edition = "2021"
description = "Hyprnote Mobile App"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "hyprnote_mobile_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true, features = ["specta"] }
tauri-plugin-deep-link = { workspace = true }
tauri-plugin-dialog = { workspace = true }
tauri-plugin-http = { workspace = true }
tauri-plugin-store = { workspace = true }

tauri-plugin-auth = { workspace = true }
tauri-plugin-db = { workspace = true }
tauri-plugin-misc = { workspace = true }
tauri-plugin-template = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

specta = { workspace = true }
specta-typescript = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }

thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

openssl-sys = { version = "0.9", features = ["vendored"] }
