[package]
name = "whisper-local-model"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
