[package]
name = "whisper"
version = "0.1.0"
edition = "2021"

[features]
default = []
local = ["whisper-rs", "lazy_static", "regex"]
cloud = []

[dev-dependencies]
hypr-data = { workspace = true }
hypr-llama = { workspace = true }

dirs = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[dependencies]
hypr-audio-utils = { workspace = true }
hypr-ws = { workspace = true }

bytes = { workspace = true }
cpal = { workspace = true }
futures-util = { workspace = true }
kalosm-sound = { workspace = true, default-features = false }
rodio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

lazy_static = { workspace = true, optional = true }
regex = { workspace = true, optional = true }

[target.'cfg(not(target_os = "macos"))'.dependencies]
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", rev = "e3d67d5", features = ["raw-api", "tracing_backend"], optional = true }

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", rev = "e3d67d5", features = ["raw-api", "tracing_backend"], optional = true }

[target.'cfg(all(target_os = "macos", target_arch = "x86_64"))'.dependencies]
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", rev = "e3d67d5", features = ["raw-api", "tracing_backend"], optional = true }
