[package]
name = "llama"
version = "0.1.0"
edition = "2021"

[dependencies]
hypr-gguf = { workspace = true }

encoding_rs = "0.8.35"
gbnf-validator = { workspace = true }

async-openai = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tokio-stream = { workspace = true }

serde = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_os = "macos"))'.dependencies]
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs", default-features = false, features = ["openmp"], branch = "update-llama-cpp-2025-06-04" }

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]

llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs", features = ["openmp", "metal"], branch = "update-llama-cpp-2025-05-28" }

[target.'cfg(all(target_os = "macos", target_arch = "x86_64"))'.dependencies]
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs", features = ["native"], branch = "update-llama-cpp-2025-06-04" }

[dev-dependencies]
hypr-buffer = { workspace = true }
hypr-data = { workspace = true }
hypr-gbnf = { workspace = true }
hypr-listener-interface = { workspace = true }
hypr-template = { workspace = true }

dirs = { workspace = true }
rand = "0.9.0"
serde_json = { workspace = true }
