[package]
name = "pyannote"
version = "0.1.0"
edition = "2021"

[features]
default = []
cloud = ["reqwest", "url"]
local = ["hypr-onnx", "knf-rs"]
knf-rs = ["dep:knf-rs"]

[dependencies]
reqwest = { workspace = true, features = ["json"], optional = true }
url = { workspace = true, optional = true }

hypr-onnx = { workspace = true, optional = true }
knf-rs = { git = "https://github.com/thewh1teagle/pyannote-rs", rev = "e3abad6", package = "knf-rs", optional = true }

anyhow = { workspace = true }
thiserror = { workspace = true }

serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }

[dev-dependencies]
hypr-data = { workspace = true }

approx = { workspace = true }
hound = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["rt", "macros"] }
